# -*- coding: utf-8 -*-
"""English copy for Fileloka tool pages.

Style rules (humanizer pass, Sep 2026): plain words, straight quotes,
no em dashes, no "no X, no Y, no Z" lists, say what the tool actually does.
"""
P = {
 "merge-pdf": dict(
   title="Merge PDF Files Online Free, Without Uploading | Fileloka",
   h1="Merge PDF files into one",
   lead="Put two or more PDFs together in the order you want. Your browser does the joining, so contracts and invoices stay on your own laptop or phone the whole time.",
   meta="Combine several PDF files into one for free. Reorder them first, then merge in your browser. The files are never uploaded anywhere.",
   steps=["Pick two or more PDFs, or drop them anywhere on the page.",
          "Use the arrows to put them in order. Each file shows its page count.",
          "Click Merge and download the combined PDF."],
   faqs=[("How many PDFs can I merge at once?",
          "There's no set limit. What your device can hold in memory is the real ceiling, and a few dozen ordinary documents is fine on any recent phone or laptop."),
         ("Will merging lower the quality?",
          "No. Pages are copied over as they are, so text stays selectable, images keep their resolution and links still work."),
         ("Can I merge password protected PDFs?",
          "Not yet. Locked files are marked in the list and skipped. Remove the password first, then merge."),
         ("How is this safer than other merge sites?",
          "Most merge sites upload your files, process them on their server and promise to delete them later. Here the merge happens in your browser. Open the Network tab in your browser's developer tools and you'll see nothing being sent.")],
   related=["split-pdf","compress-pdf","jpg-to-pdf"]),
 "split-pdf": dict(
   title="Split PDF and Extract Pages Online Free | Fileloka",
   h1="Split a PDF or pull out the pages you need",
   lead="Take specific pages or ranges out of a PDF (say 1-3 and 7), or save every page as its own file. It all runs on your device, so the document never goes to a server.",
   meta="Extract pages from a PDF or split every page into its own file, free and without uploading. Type ranges like 1-3, 7 and download.",
   steps=["Pick the PDF you want to split, or drop it on the page.",
          "Choose a mode: extract a range such as 1-3, 7, or save every page as a separate PDF.",
          "Download the result. Lots of files come as one ZIP."],
   faqs=[("How do I take just a few pages out of a PDF?",
          "Choose 'Extract pages' and type the page numbers. 5, 2-4 and 1-3, 7, 12 all work. You get a new PDF with only those pages, in that order."),
         ("Can I save every page as a separate PDF?",
          "Yes. Pick 'Every page as its own PDF' and you'll get a ZIP with one numbered file per page. Handy for splitting up a batch of scans."),
         ("Does splitting remove the text?",
          "No. Pages are copied, not re-rendered, so you can still select, search and copy the text. Images keep their full resolution."),
         ("Is my document uploaded?",
          "No. The file is read into your browser's memory, split there and dropped when you close the tab. You can even go offline after the page loads and it keeps working.")],
   related=["merge-pdf","pdf-to-jpg","compress-pdf"]),
 "compress-pdf": dict(
   title="Compress PDF Online Free, Down to 100 KB | Fileloka",
   h1="Compress a PDF and keep the text sharp",
   lead="Shrink a PDF in your browser. Smart mode only recompresses the photos and scans inside, so the text stays selectable. If a form wants something like 200 KB or 1 MB, pick Target size and Fileloka finds the best quality that still fits.",
   meta="Compress PDF files for free without uploading. Smart mode keeps text selectable, and Target size fits your PDF under 100 KB, 200 KB, 500 KB or 1 MB.",
   steps=["Pick the PDF you want to shrink, or drop it on the page.",
          "Choose Smart (keeps text), Target size (for example 200 KB) or Maximum (smallest file).",
          "Check the before and after sizes, then download."],
   faqs=[("How much smaller will my PDF get?",
          "That depends on what's in it. Scans and photo heavy PDFs often lose 50 to 90 percent. A PDF that's mostly text is already small and may barely change, and the size meter will tell you so."),
         ("How do I compress a PDF to exactly 200 KB?",
          "Choose Target size, click 200 KB (or type your own number) and press Compress. Fileloka tries to keep the text first. If that isn't enough, it searches for the highest image quality that still fits, so you don't have to fiddle with a slider."),
         ("What's the difference between Smart and Maximum?",
          "Smart only touches the images embedded in the PDF. Text, links and drawings stay exactly as they were. Maximum redraws every page as a picture, which gives the smallest file, but you can't select or search the text afterwards."),
         ("Is it safe to compress confidential PDFs here?",
          "Yes. The compression runs on your device and the file isn't sent anywhere. That's how the tool is built, not a promise in a privacy policy. There is simply no server that receives your file.")],
   related=["merge-pdf","split-pdf","compress-image"]),
 "pdf-to-jpg": dict(
   title="PDF to JPG Converter Online Free | Fileloka",
   h1="Turn PDF pages into JPG images",
   lead="Save every page of a PDF as a JPG for slides, chat apps or documents. Set the quality and detail, check the thumbnails, then grab one image or a ZIP of all of them.",
   meta="Convert PDF pages to JPG for free without uploading. Choose quality and resolution, preview the pages, download single images or a ZIP.",
   steps=["Pick a PDF or drop it on the page.",
          "Set the JPG quality and detail level (screen, print or maximum).",
          "Convert, look over the thumbnails, and download the images one by one or as a ZIP."],
   faqs=[("What resolution are the JPGs?",
          "You choose. Good (screen) renders at about 1.5 times the page size, Sharp (print) at 2 times and Maximum at 3 times. More detail means bigger files."),
         ("Can I convert just one page?",
          "Convert the document, then download only the page you need. Each page comes out as its own numbered image."),
         ("Why do some PDFs take longer?",
          "Your device renders every page with pdf.js, the same engine Firefox uses to show PDFs. Long or graphics heavy documents are simply more work. The progress bar shows how far along it is."),
         ("Is the PDF uploaded during conversion?",
          "No. pdf.js renders the pages in your browser. You can check the Network tab and see that nothing is sent.")],
   related=["jpg-to-pdf","compress-image","split-pdf"]),
 "jpg-to-pdf": dict(
   title="JPG to PDF: Combine Images into a PDF Free | Fileloka",
   h1="Turn photos and scans into one PDF",
   lead="Put JPG, PNG or WebP images into a single PDF. Change the order, match each image's size or use A4, add a margin if you like. Your photos stay on your device.",
   meta="Convert JPG, PNG or WebP images to one PDF for free, without uploading. Reorder pages, choose A4 or original size, add margins.",
   steps=["Pick your images or drop them on the page. Mixed formats are fine.",
          "Put them in order and choose a page size: match each image, A4 portrait or A4 landscape.",
          "Click Make PDF and download it."],
   faqs=[("Can I combine photos from my phone into one PDF?",
          "Yes, that's what most people use it for. Select all the photos, sort them and save one PDF that's easy to email. iPhone HEIC photos need converting first with the HEIC to JPG tool."),
         ("Which page size should I pick?",
          "'Match image' keeps each photo's own proportions, which suits screenshots. A4 puts every image neatly on a standard page, which is better for printing or official forms."),
         ("Are my images compressed?",
          "JPGs go in unchanged, so there's no quality loss. PNG and WebP are embedded losslessly too."),
         ("Is this really private?",
          "Yes. pdf-lib builds the PDF in your browser's memory. The photos aren't sent or stored anywhere.")],
   related=["heic-to-jpg","compress-image","pdf-to-jpg"]),
 "heic-to-jpg": dict(
   title="HEIC to JPG Converter for iPhone Photos, Free | Fileloka",
   h1="Convert iPhone HEIC photos to JPG",
   lead="iPhones save photos as HEIC, and Windows, older apps and plenty of upload forms won't open them. This turns them into ordinary JPGs, decoded on your own device.",
   meta="Convert iPhone HEIC photos to JPG for free, without uploading. Convert many at once and set the quality. Decoding happens in your browser.",
   steps=["Pick your .heic or .heif photos, or drop several at once.",
          "Choose JPG (opens everywhere) or PNG, and set the quality.",
          "Convert, then download each photo or all of them as a ZIP."],
   faqs=[("Why won't HEIC files open on Windows?",
          "HEIC is Apple's format. Windows and many websites need an extra codec or refuse the file. JPG opens on every device and every upload form accepts it."),
         ("Can I convert lots of iPhone photos at once?",
          "Yes. Drop as many as you like and they're converted one after another with a progress bar. Your device does the work, so there's no upload queue to wait on."),
         ("Do I lose quality going to JPG?",
          "JPG is lossy, but at the default 88 percent you won't see a difference when viewing or printing. Pick PNG if you need an exact copy, though the files will be much bigger."),
         ("How does this work without a server?",
          "The page loads libheif, an open source decoder compiled to JavaScript (about 0.5 MB, once). Your browser then decodes the photos itself, which is also why it keeps working if you go offline.")],
   related=["compress-image","jpg-to-pdf","convert-image"]),
 "compress-image": dict(
   title="Compress JPG, PNG and WebP Images Online Free | Fileloka",
   h1="Compress images and keep them sharp",
   lead="Make photos much smaller for web forms, email and faster websites. Compress JPG, PNG and WebP in batches, cap the width if you want, and see exactly how much each file saved.",
   meta="Compress JPG, PNG and WebP images for free without uploading. Batch processing, quality control and max width. EXIF data is removed automatically.",
   steps=["Pick one or more images, or drop them on the page.",
          "Set the quality, the output format (JPG, WebP or keep original) and a max width if you need one.",
          "Compress and download each file or a ZIP. Before and after sizes are shown for every image."],
   faqs=[("How much smaller will my photos get?",
          "Phone photos usually shrink by 60 to 90 percent at the default quality and look the same on screen. You'll see the exact size of every file in the results."),
         ("What happens to the hidden data in my photos?",
          "Saving as JPG or WebP strips the EXIF data, which includes GPS location, camera model and timestamps. Worth knowing if you're posting photos publicly."),
         ("Why didn't my PNG get smaller?",
          "PNG is lossless, so the quality slider doesn't do anything. Set a max width to shrink its dimensions, or convert it to JPG or WebP for a big saving."),
         ("Are my photos uploaded?",
          "No. Your browser's own image engine does the compression on your device, which is also why it's fast.")],
   related=["heic-to-jpg","resize-image","convert-image"]),
 "resize-image": dict(
   title="Resize Images Online Free, by Pixels or Percent | Fileloka",
   h1="Resize images to exact pixels or a percentage",
   lead="Scale pictures to the size a profile photo, marketplace or form asks for. Keep the proportions automatically or set exact width and height, for one image or a whole batch.",
   meta="Resize JPG, PNG and WebP images for free without uploading. Exact pixel sizes or percentage scaling, batch support, proportions kept automatically.",
   steps=["Pick the images you want to resize, or drop them on the page.",
          "Type a width, a height or both in pixels. Or switch to percent.",
          "Resize and download. The new size is added to each file name."],
   faqs=[("How do I resize without stretching the image?",
          "Leave 'Keep proportions' on. Enter only a width (or only a height) and the other side is worked out for you. If you enter both, the image is fitted inside that box without distortion."),
         ("Can I make an image bigger?",
          "Yes, both modes can upscale. Browsers smooth the result nicely, but anything much past 2 times will look soft. That's just how enlarging works."),
         ("Does resizing reduce quality?",
          "Shrinking keeps images crisp. JPGs are saved at 92 percent quality, which you won't notice on photos. PNGs stay lossless."),
         ("Are my pictures uploaded?",
          "No. Resizing happens in your browser's canvas on your device.")],
   related=["compress-image","convert-image","jpg-to-pdf"]),
 "convert-image": dict(
   title="Convert Images to JPG, PNG or WebP Online Free | Fileloka",
   h1="Convert images between JPG, PNG and WebP",
   lead="Change formats in one click. WebP screenshots to JPG so they open everywhere, JPG to PNG for editing, anything to WebP for smaller web images. Works in batches and nothing gets uploaded.",
   meta="Convert images between JPG, PNG and WebP for free without uploading. Batch conversion with quality control, right in your browser.",
   steps=["Pick the images to convert. Mixed formats are fine.",
          "Choose the target format and, for JPG or WebP, the quality.",
          "Convert and download them one at a time or as a ZIP."],
   faqs=[("Which format should I pick?",
          "JPG for photos and anything that has to open everywhere. PNG for screenshots, logos and transparency. WebP when you want the smallest files for a website. If you're not sure, JPG is the safe choice."),
         ("What happens to transparency in a JPG?",
          "JPG can't store transparency, so transparent areas get a white background. We'd rather tell you now than surprise you with black boxes."),
         ("Why can't I choose WebP?",
          "Some browsers, mostly older Safari, can't save WebP. When that's the case the option is hidden and a note explains why. JPG and PNG work everywhere."),
         ("Is the conversion done on a server?",
          "No. Your browser re-encodes the images on your device, which is why it feels instant.")],
   related=["compress-image","resize-image","pdf-to-jpg"]),
 "qr-code": dict(
   title="Free QR Code Generator, PNG Download | Fileloka",
   h1="Make a QR code for a link or any text",
   lead="Type a link or some text and get a clean QR code you can put on a screen, a flyer or a poster. You don't need an account, there's no watermark, and the code is made on your device.",
   meta="Make QR codes for free with no sign-up and no watermark. Download a PNG sized for screen, print or posters. Created in your browser.",
   steps=["Type or paste the link or text.",
          "Pick a size: 256 px for screens, 512 px for print, 1024 px for posters.",
          "Generate it and download the PNG."],
   faqs=[("Do these QR codes expire?",
          "Never. The code contains your text or link directly. There's no redirect service in between that could shut down or start charging."),
         ("Can I use them commercially?",
          "Yes. Put them on packaging, menus or flyers. The image is yours and you don't need to credit anyone."),
         ("How much text fits in a QR code?",
          "A link or a few hundred characters is comfortable. If you paste something too long the tool tells you. Shorter content also scans faster from further away."),
         ("Is what I type sent anywhere?",
          "No. The code is drawn in your browser, which matters when it holds a private link, Wi-Fi details or contact info.")],
   related=["password-generator","word-counter","signature"]),
 "password-generator": dict(
   title="Strong Random Password Generator, Free | Fileloka",
   h1="Generate a strong random password",
   lead="Make properly random passwords with your browser's cryptographic generator. You set the length, the character types and whether to skip look-alike characters. The meter shows entropy in bits instead of a vague colour.",
   meta="Free strong password generator that runs on your device. Cryptographically random, adjustable length and characters, entropy shown in bits.",
   steps=["Set the length (16 or more is a good idea) and which character types to use.",
          "Turn on 'avoid look-alikes' (l, 1, O, 0) if you'll be typing the password by hand.",
          "Copy it. Changing any setting makes a fresh one."],
   faqs=[("Is this generator actually secure?",
          "Yes. It uses crypto.getRandomValues, the same randomness source password managers rely on, with unbiased sampling, and it makes sure every character type you picked shows up. The code is open source if you want to check."),
         ("What do the entropy bits mean?",
          "Entropy is a measure of how hard a password is to brute force. Roughly, 45 bits is weak, 70 is fair and 100 or more is excellent. A 16 character password using every character type comes out around 100 bits."),
         ("Is my password stored or sent anywhere?",
          "No. It's created in your browser's memory and only exists on your screen and clipboard. Refresh the page and it's gone."),
         ("Should I avoid look-alike characters?",
          "Turn it on for passwords you'll read and type yourself, like Wi-Fi or a TV login. For passwords that live in a password manager, leave it off for a slightly bigger pool of characters.")],
   related=["qr-code","word-counter","signature"]),
 "word-counter": dict(
   title="Word Counter with Characters and Reading Time | Fileloka",
   h1="Count words, characters and reading time",
   lead="Paste or type your text and the counts update as you go: words, characters with and without spaces, sentences, paragraphs, unique words, plus rough reading and speaking time. Useful for essays, ads and speeches.",
   meta="Free live word counter: words, characters, sentences, paragraphs, unique words, reading and speaking time. Your text stays in your browser.",
   steps=["Paste or type your text into the box.",
          "The counts update while you edit. There's no button to press.",
          "Use reading time (about 220 words a minute) and speaking time (about 130) to hit your limits."],
   faqs=[("How is reading time worked out?",
          "Reading time assumes about 220 words per minute, a typical adult reading silently. Speaking time assumes about 130, a comfortable pace for a talk. Treat both as estimates."),
         ("Does it help with character limits?",
          "Yes. Both character counts update live, so you can trim a bio, an ad or a meta description to the exact limit while you type."),
         ("What counts as a sentence or a paragraph?",
          "Sentences end with a full stop, exclamation mark or question mark. Paragraphs are separated by blank lines. Text with no ending punctuation still counts as one sentence."),
         ("Is my text saved or sent anywhere?",
          "No. The counting happens in your browser as you type and nothing is stored. Paste confidential drafts without worrying.")],
   related=["password-generator","qr-code","signature"]),
 "signature": dict(
   title="Draw Your Signature Online, Transparent PNG | Fileloka",
   h1="Draw your signature and save it as a PNG",
   lead="Sign with a mouse, a finger or a stylus and download a clean signature image. Use the transparent PNG on documents, or a white background for forms. Strokes are smoothed and you can undo.",
   meta="Draw a handwritten signature online for free with a mouse or touch screen, and download a transparent PNG. Runs on your device.",
   steps=["Draw your signature on the pad with a mouse, finger or stylus.",
          "Change the pen colour and thickness. Undo removes the last stroke.",
          "Download the PNG. It's transparent unless you tick white background."],
   faqs=[("How do I put the signature on a PDF or document?",
          "Download the transparent PNG and insert it as an image in Word, Google Docs or your PDF editor, then drag it onto the signature line. The transparent background lets it sit naturally on the page."),
         ("Is a drawn signature legally valid?",
          "For everyday documents in many countries, usually yes. For important contracts, check what the other side requires. This tool makes the image; it isn't a certified e-signature."),
         ("Why does my signature look smooth?",
          "Strokes are drawn with curve smoothing at high resolution, so the PNG looks crisp even if you signed with a fingertip on a phone."),
         ("Is my signature uploaded or stored?",
          "No. It exists in your browser while you draw and in the PNG you download. Close the tab and it's gone, which is what you want for something this personal.")],
   related=["jpg-to-pdf","merge-pdf","word-counter"]),
}
