# -*- coding: utf-8 -*-
"""Konten Bahasa Indonesia untuk halaman /id/ Fileloka.
Ditulis untuk intent pencarian orang Indonesia (bukan terjemahan literal)."""

P_ID = {
 "merge-pdf": dict(
   title="Gabung PDF Online Gratis — Tanpa Upload | Fileloka",
   h1="Gabungkan beberapa PDF jadi satu file",
   lead="Satukan dua atau lebih file PDF menjadi satu dokumen, dengan urutan yang kamu tentukan sendiri. Bedanya dari situs lain: file kamu tidak pernah di-upload — semuanya diproses di HP atau laptopmu sendiri, jadi aman untuk ijazah, kontrak, dan berkas penting lainnya.",
   meta="Cara menggabungkan file PDF jadi satu, gratis dan tanpa upload. Atur urutan halaman, proses langsung di perangkatmu, hasil langsung terunduh.",
   steps=["Pilih atau jatuhkan dua file PDF atau lebih — dari HP maupun laptop.",
          "Atur urutannya dengan tombol panah; jumlah halaman tiap file ikut ditampilkan.",
          "Klik Gabung, lalu unduh satu PDF hasil gabungan."],
   faqs=[("Bagaimana cara menggabungkan PDF di HP?",
          "Buka halaman ini di browser HP (Chrome atau Safari), ketuk area pilih file, ambil PDF dari penyimpanan atau WhatsApp, atur urutan, lalu ketuk Gabung. Tidak perlu install aplikasi apa pun."),
         ("Apakah ada batas jumlah atau ukuran file?",
          "Tidak ada batas buatan. Batasnya hanya memori perangkatmu — menggabungkan puluhan dokumen biasa lancar di HP maupun laptop keluaran sekarang."),
         ("Apakah kualitas dokumen berubah setelah digabung?",
          "Tidak. Halaman disalin apa adanya ke file baru — teks tetap bisa diseleksi dan dicari, gambar tetap tajam, dan tautan tetap berfungsi."),
         ("Apakah file saya benar-benar aman?",
          "Ya, karena tidak pernah dikirim ke mana-mana. Situs lain meng-upload file-mu ke server mereka lalu berjanji menghapusnya; di sini tidak ada servernya sama sekali. Buktikan sendiri: setelah halaman terbuka, aktifkan mode pesawat — alat ini tetap jalan.")],
   related=["split-pdf","compress-pdf","jpg-to-pdf"]),

 "split-pdf": dict(
   title="Pisah PDF & Ambil Halaman Tertentu Gratis | Fileloka",
   h1="Pisahkan PDF — ambil halaman yang kamu butuhkan",
   lead="Ekstrak halaman atau rentang tertentu dari sebuah PDF (misalnya 1-3, 7), atau simpan setiap halaman sebagai file terpisah. Diproses sepenuhnya di perangkatmu — salah satu dari sedikit pemisah PDF yang tidak pernah melihat isi dokumenmu.",
   meta="Ambil halaman tertentu dari PDF atau pecah setiap halaman jadi file sendiri — gratis, tanpa upload. Ketik rentang seperti 1-3, 7 lalu unduh.",
   steps=["Pilih atau jatuhkan PDF yang mau dipisah.",
          "Pilih mode: ambil rentang halaman (contoh: 1-3, 7) atau simpan tiap halaman jadi PDF sendiri.",
          "Unduh hasilnya — berupa satu PDF, atau ZIP kalau filenya banyak."],
   faqs=[("Bagaimana cara mengambil satu halaman saja dari PDF?",
          "Pilih mode “Ambil halaman”, ketik nomor halamannya (misalnya 5 saja, atau 2-4, atau kombinasi 1-3, 7), lalu unduh PDF baru yang berisi halaman itu saja."),
         ("Bisa memecah PDF jadi file per halaman?",
          "Bisa. Pilih “Setiap halaman jadi PDF sendiri” dan kamu mendapat ZIP berisi satu PDF bernomor per halaman — praktis untuk memecah hasil scan atau materi yang mau dibagikan terpisah."),
         ("Apakah teks masih bisa dicari setelah dipisah?",
          "Ya. Halaman disalin, bukan difoto ulang — teks tetap bisa diseleksi, dicari, dan di-copy seperti aslinya."),
         ("Apakah dokumen saya di-upload saat diproses?",
          "Tidak pernah. File dibaca ke memori browser-mu, dipisah di situ, dan hilang saat tab ditutup. Kamu bahkan bisa memutus internet setelah halaman terbuka — alatnya tetap bekerja.")],
   related=["merge-pdf","pdf-to-jpg","compress-pdf"]),

 "compress-pdf": dict(
   title="Kompres PDF Online Gratis — Tanpa Upload | Fileloka",
   h1="Kompres PDF sampai lolos batas unggah",
   lead="Perkecil ukuran PDF langsung di browser — untuk lampiran email, unggah berkas lamaran, atau syarat maksimal seperti 200 KB di formulir online. Dua mode: Balanced menjaga teks tetap bisa diseleksi, Strong mengejar ukuran sekecil mungkin — dan kamu melihat ukuran sebelum/sesudah sebelum mengunduh.",
   meta="Cara kompres PDF gratis tanpa upload — termasuk memperkecil ke batas seperti 200 KB. Dua mode kompresi, ukuran sebelum-sesudah ditampilkan jujur.",
   steps=["Pilih atau jatuhkan PDF yang mau dikecilkan.",
          "Pilih Balanced (teks tetap bisa diseleksi) atau Strong (paling kecil), lalu atur kualitas gambarnya bila perlu.",
          "Bandingkan ukuran sebelum/sesudah, lalu unduh hasilnya."],
   faqs=[("Bagaimana cara kompres PDF jadi 200 KB?",
          "Pakai mode Strong, mulai dari kualitas 60–70%, lalu lihat angka hasil di layar. Kalau masih di atas target, turunkan kualitasnya bertahap. Dokumen hasil scan atau banyak foto paling mudah menyusut; PDF berisi teks murni memang sudah kecil dari sananya."),
         ("Apa bedanya mode Balanced dan Strong?",
          "Balanced menata ulang isi file dan menjaga teks tetap bisa diseleksi serta dicari. Strong menggambar ulang tiap halaman sebagai gambar terkompresi — jauh lebih kecil, tapi teksnya tidak bisa diseleksi lagi. Untuk berkas yang akan dibaca petugas, Strong biasanya aman; untuk dokumen yang masih akan diedit, pakai Balanced."),
         ("Apakah hasilnya masih jelas terbaca?",
          "Ya — kamu yang pegang kendali kualitasnya lewat slider, dan pengaturan bawaannya menjaga dokumen tetap nyaman dibaca di layar maupun saat dicetak."),
         ("Aman tidak untuk dokumen penting seperti ijazah atau KTP?",
          "Aman, justru karena tidak pernah di-upload. Kompresi terjadi di perangkatmu sendiri; tidak ada server yang bisa menyimpan atau membocorkannya. Ini jaminan dari cara kerjanya, bukan sekadar janji kebijakan.")],
   related=["merge-pdf","split-pdf","compress-image"]),

 "pdf-to-jpg": dict(
   title="PDF ke JPG Online Gratis — Tanpa Upload | Fileloka",
   h1="Ubah halaman PDF jadi gambar JPG",
   lead="Konversi setiap halaman PDF menjadi gambar JPG berkualitas — untuk dikirim lewat WhatsApp, dijadikan slide, atau ditempel ke dokumen lain. Atur kualitas dan ketajaman, lihat pratinjaunya, lalu unduh satuan atau sekaligus dalam ZIP.",
   meta="Ubah PDF jadi gambar JPG gratis tanpa upload. Atur kualitas dan resolusi, pratinjau tiap halaman, unduh satuan atau ZIP.",
   steps=["Pilih atau jatuhkan file PDF.",
          "Atur kualitas JPG dan tingkat detail (layar, cetak, atau maksimum).",
          "Konversi, lihat pratinjau, lalu unduh gambar yang kamu butuhkan atau semuanya sebagai ZIP."],
   faqs=[("Bisa mengubah satu halaman saja jadi JPG?",
          "Bisa. Konversi dokumennya, lalu di daftar hasil unduh hanya halaman yang kamu perlukan — setiap halaman menjadi gambar bernomor sendiri."),
         ("Seberapa tajam hasil gambarnya?",
          "Kamu yang memilih: “Layar” cukup untuk dikirim-kirim, “Cetak” dua kali lebih tajam, “Maksimum” untuk kebutuhan detail tinggi. Semakin tajam, semakin besar ukuran filenya."),
         ("Kenapa PDF tertentu butuh waktu lebih lama?",
          "Karena setiap halaman benar-benar dirender oleh perangkatmu sendiri (mesin yang sama dengan penampil PDF Firefox). Dokumen panjang atau penuh grafis butuh kerja lebih — ada progress bar yang menemani."),
         ("Apakah isi PDF saya dikirim ke server?",
          "Tidak. Rendering terjadi lokal di browser-mu. Bisa kamu buktikan lewat tab Network di DevTools — tidak ada file yang keluar.")],
   related=["jpg-to-pdf","compress-image","split-pdf"]),

 "jpg-to-pdf": dict(
   title="Ubah Foto & JPG ke PDF Online Gratis | Fileloka",
   h1="Ubah foto dan scan jadi satu PDF rapi",
   lead="Kumpulkan foto, scan, dan tangkapan layar (JPG, PNG, atau WebP) menjadi satu dokumen PDF — untuk berkas lamaran, tugas kuliah, atau arsip. Atur urutan, pilih ukuran halaman mengikuti foto atau A4, tambah margin — tanpa fotomu meninggalkan perangkat.",
   meta="Cara mengubah foto atau JPG jadi PDF di HP dan laptop — gratis, tanpa upload. Atur urutan, pilih A4 atau ukuran asli, langsung unduh.",
   steps=["Pilih atau jatuhkan foto-fotomu — boleh banyak sekaligus, format campur tidak masalah.",
          "Atur urutannya, lalu pilih ukuran halaman: mengikuti foto, A4 tegak, atau A4 mendatar.",
          "Klik Buat PDF dan unduh dokumen jadinya."],
   faqs=[("Bagaimana cara mengubah foto jadi PDF di HP?",
          "Buka halaman ini di browser HP, ketuk pilih gambar, ambil foto dari galeri (boleh lebih dari satu), atur urutan, lalu ketuk Buat PDF. Hasilnya langsung tersimpan ke perangkatmu — tanpa aplikasi tambahan."),
         ("Sebaiknya pilih ukuran halaman yang mana?",
          "“Mengikuti foto” menjaga proporsi asli setiap gambar — pas untuk tangkapan layar. A4 menempatkan tiap foto rapi di halaman standar — pas untuk dicetak atau syarat unggah berkas resmi."),
         ("Apakah kualitas foto menurun?",
          "Foto JPG dimasukkan apa adanya tanpa dikompres ulang. PNG dan WebP juga dibungkus tanpa kehilangan kualitas."),
         ("Foto iPhone (HEIC) bisa tidak?",
          "Belum — format HEIC perlu diubah dulu ke JPG (di iPhone: ubah setelan kamera ke Most Compatible, atau ekspor ulang fotonya). Dukungan HEIC ada di rencana pengembangan.")],
   related=["pdf-to-jpg","compress-image","merge-pdf"]),

 "compress-image": dict(
   title="Kompres Foto Online Gratis — JPG, PNG, WebP | Fileloka",
   h1="Kompres foto tanpa merusak tampilannya",
   lead="Kecilkan ukuran foto secara drastis — untuk formulir online yang membatasi ukuran, lampiran email, atau supaya website-mu cepat — sambil tetap terlihat tajam. Bisa banyak file sekaligus, dengan penghematan per file ditampilkan jujur. Bonus privasi: metadata EXIF (lokasi GPS, tipe kamera) ikut terhapus otomatis.",
   meta="Kompres foto online gratis tanpa upload — kecilkan JPG, PNG, WebP untuk formulir dan email. Banyak file sekaligus, EXIF terhapus otomatis.",
   steps=["Pilih atau jatuhkan satu atau banyak foto sekaligus.",
          "Atur kualitas, format keluaran (JPG, WebP, atau format asli), dan lebar maksimum bila perlu.",
          "Kompres, lalu unduh per file atau semuanya dalam ZIP — lengkap dengan ukuran sebelum/sesudah."],
   faqs=[("Bagaimana cara kompres foto jadi 100–200 KB?",
          "Pakai format JPG dengan kualitas sekitar 70%, dan isi “lebar maksimum” misalnya 1200–1600 piksel — kombinasi keduanya yang paling menentukan. Angka hasil tiap foto ditampilkan, jadi kamu bisa menyesuaikan sampai pas di bawah batas formulir."),
         ("Kenapa foto PNG saya tidak mengecil?",
          "PNG itu format lossless, jadi slider kualitas tidak berlaku. Solusinya: isi lebar maksimum untuk memperkecil dimensinya, atau ubah formatnya ke JPG/WebP — penyusutannya langsung besar."),
         ("Apa itu metadata EXIF dan kenapa dihapus?",
          "EXIF adalah data tersembunyi di dalam foto: titik GPS tempat foto diambil, tanggal, dan tipe HP/kamera. Saat foto dikompres ulang ke JPG atau WebP, data ini otomatis terbuang — lebih aman kalau fotonya akan dibagikan ke publik."),
         ("Apakah foto saya di-upload untuk dikompres?",
          "Tidak — kompresi memakai mesin gambar milik browser-mu sendiri. Karena tidak ada proses upload, hasilnya juga jauh lebih cepat: tidak ada antrean menunggu server.")],
   related=["resize-image","convert-image","jpg-to-pdf"]),

 "resize-image": dict(
   title="Resize Foto Online — Ubah Ukuran ke Piksel Persis | Fileloka",
   h1="Ubah ukuran foto ke piksel yang kamu mau",
   lead="Atur dimensi gambar dengan presisi — untuk foto profil, syarat unggah formulir, marketplace, atau dokumen. Jaga proporsi otomatis supaya foto tidak gepeng, atau tentukan lebar × tinggi persis. Bisa banyak file sekaligus, diproses di perangkatmu sendiri.",
   meta="Resize foto online gratis tanpa upload — ubah ukuran gambar ke piksel persis atau persentase, proporsi terjaga otomatis, bisa banyak file.",
   steps=["Pilih atau jatuhkan foto yang mau diubah ukurannya.",
          "Masukkan lebar dan/atau tinggi dalam piksel — atau pakai mode persen.",
          "Klik Resize dan unduh; ukuran baru otomatis tertulis di nama file."],
   faqs=[("Bagaimana mengubah ukuran tanpa membuat foto gepeng?",
          "Biarkan “Jaga proporsi” menyala. Isi lebarnya saja (atau tingginya saja), sisi lain dihitung otomatis; kalau keduanya diisi, foto dimuat pas tanpa distorsi."),
         ("Bisa memperbesar foto kecil?",
          "Bisa, baik dalam piksel maupun persen. Browser memakai penghalusan berkualitas tinggi, tapi pembesaran lebih dari ±2× tetap akan terlihat lembut — itu batas fisika, bukan alatnya."),
         ("Apakah kualitasnya turun saat diperkecil?",
          "Memperkecil justru menjaga ketajaman. Keluaran JPG disimpan pada kualitas 92% — untuk foto, selisihnya tak terlihat mata. PNG tetap lossless."),
         ("Foto saya dikirim ke server tidak?",
          "Tidak. Proses resize memakai canvas milik browser, sepenuhnya lokal. Fotomu tidak pernah meninggalkan perangkat.")],
   related=["compress-image","convert-image","jpg-to-pdf"]),

 "convert-image": dict(
   title="WebP ke JPG, PNG ke JPG & Sebaliknya Gratis | Fileloka",
   h1="Konversi gambar antara JPG, PNG, dan WebP",
   lead="Tukar format dalam sekali klik — paling sering: gambar WebP hasil unduhan yang tidak bisa dibuka aplikasi lama, diubah ke JPG supaya kompatibel di mana saja. Bisa banyak file sekaligus, dengan kendali kualitas, tanpa upload.",
   meta="Konversi WebP ke JPG, PNG ke JPG, dan sebaliknya — gratis, tanpa upload, banyak file sekaligus, langsung di browser HP atau laptop.",
   steps=["Pilih atau jatuhkan gambar-gambarnya — format asal boleh campur.",
          "Pilih format tujuan; untuk JPG/WebP atur juga kualitasnya.",
          "Konversi lalu unduh satuan atau semuanya dalam ZIP."],
   faqs=[("Bagaimana cara mengubah WebP ke JPG?",
          "Jatuhkan file WebP-nya, pilih format tujuan JPG, klik Konversi, unduh. Selesai dalam hitungan detik karena tidak ada proses upload sama sekali."),
         ("Apa yang terjadi pada bagian transparan saat jadi JPG?",
          "JPG tidak mengenal transparansi, jadi area transparan otomatis diberi latar putih bersih — diberitahukan di awal, bukan tiba-tiba jadi kotak hitam."),
         ("Sebaiknya pilih format apa?",
          "JPG untuk foto dan kompatibilitas maksimal, PNG untuk tangkapan layar/logo/yang butuh transparansi, WebP untuk file terkecil di web modern. Ragu? JPG pilihan teraman."),
         ("Konversinya dilakukan di server?",
          "Tidak — mesin gambar browser-mu sendiri yang mengodekan ulang, sepenuhnya lokal. Itu juga alasan prosesnya instan.")],
   related=["compress-image","resize-image","pdf-to-jpg"]),

 "qr-code": dict(
   title="Buat QR Code Gratis — Tanpa Watermark & Daftar | Fileloka",
   h1="Buat QR code untuk link atau teks apa pun",
   lead="Ketik tautan, teks, atau catatan Wi-Fi dan dapatkan QR code tajam siap scan dalam hitungan detik — untuk menu usaha, kartu nama, poster, atau tugas. Tanpa akun, tanpa watermark, dan kodenya dibuat di perangkatmu sendiri.",
   meta="Buat QR code gratis tanpa daftar dan tanpa watermark. Unduh PNG ukuran layar, cetak, atau poster. Dibuat lokal di browser, tidak kedaluwarsa.",
   steps=["Ketik atau tempel tautan/teksnya.",
          "Pilih ukuran: 256 px untuk layar, 512 px untuk cetak, 1024 px untuk poster.",
          "Buat kodenya, lalu unduh sebagai PNG."],
   faqs=[("Apakah QR code ini bisa kedaluwarsa?",
          "Tidak akan pernah. Yang dibuat adalah QR statis yang berisi persis teks/tautanmu — tidak lewat layanan pemendek pihak ketiga yang bisa tutup atau tiba-tiba berbayar."),
         ("Boleh dipakai untuk usaha atau jualan?",
          "Boleh sepenuhnya — untuk menu, kemasan, brosur, mana pun. Gambar hasilnya milikmu, tanpa watermark, tanpa kewajiban mencantumkan apa pun."),
         ("Berapa panjang teks yang muat?",
          "Tautan atau beberapa ratus karakter muat dengan nyaman. Kalau terlalu panjang, alat ini memberi tahu — dan konten yang lebih pendek juga lebih mudah discan dari jarak jauh."),
         ("Apakah yang saya ketik dikirim ke server?",
          "Tidak. Kode digambar lokal di browser-mu — penting kalau yang kamu masukkan adalah tautan pribadi, password Wi-Fi, atau kontak.")],
   related=["password-generator","word-counter","signature"]),

 "password-generator": dict(
   title="Generator Password Kuat & Acak Gratis | Fileloka",
   h1="Buat password kuat yang benar-benar acak",
   lead="Hasilkan password yang benar-benar acak memakai mesin kriptografi browser — panjang, jenis karakter, dan filter karakter mirip semua di tanganmu, lengkap dengan meteran entropi yang jujur, bukan sekadar warna \u201ckuat/lemah\u201d.",
   meta="Generator password kuat, acak, dan gratis — dibuat sepenuhnya di perangkatmu, tidak disimpan atau dikirim ke mana pun. Panjang dan karakter bisa diatur.",
   steps=["Atur panjang (disarankan 16+) dan jenis karakter yang mau dipakai.",
          "Aktifkan \u201chindari karakter mirip\u201d (l, 1, O, 0) untuk password yang akan diketik manual.",
          "Salin password-nya — setiap perubahan pengaturan langsung membuat password baru."],
   faqs=[("Seberapa aman generator ini?",
          "Memakai crypto.getRandomValues — sumber acak kriptografis yang sama dengan yang dipakai aplikasi password manager — dengan sampling tanpa bias dan jaminan setiap jenis karakter terpilih muncul. Kodenya open source, jadi klaim ini bisa diperiksa siapa pun."),
         ("Apa arti angka \u201cbit entropi\u201d?",
          "Entropi mengukur seberapa sulit password ditebak paksa. Kasarnya: 45 bit lemah, 70 cukup, 100+ sangat kuat. Password 16 karakter dengan semua jenis karakter ada di kisaran 100 bit — kuat untuk akun apa pun."),
         ("Apakah password saya disimpan atau dikirim?",
          "Tidak. Password dibuat di memori browser dan hanya ada di layarmu serta clipboard. Muat ulang halaman, hilang tanpa jejak."),
         ("Kapan perlu menghindari karakter mirip?",
          "Nyalakan untuk password yang akan dibaca dan diketik manual (Wi-Fi, TV). Untuk password yang disimpan di password manager, matikan saja supaya kumpulan karakternya sedikit lebih besar.")],
   related=["qr-code","word-counter","signature"]),

 "word-counter": dict(
   title="Hitung Kata & Karakter Online Live | Fileloka",
   h1="Hitung kata, karakter, dan waktu baca",
   lead="Tempel atau ketik teks dan lihat hitungan langsung: kata, karakter (dengan dan tanpa spasi), kalimat, paragraf, kata unik, plus perkiraan waktu baca dan waktu bicara — pas untuk esai, caption, artikel, dan naskah presentasi.",
   meta="Hitung kata dan karakter online secara live — kata, kalimat, paragraf, waktu baca & bicara. Teks tidak pernah dikirim ke server.",
   steps=["Tempel atau ketik teksmu ke kotak.",
          "Semua angka diperbarui langsung selagi kamu mengetik — tanpa tombol.",
          "Pakai waktu baca (~220 kata/menit) dan waktu bicara (~130 kata/menit) untuk pas dengan batasmu."],
   faqs=[("Bisa untuk mengecek batas karakter caption atau bio?",
          "Bisa — hitungan karakter (dengan dan tanpa spasi) berubah langsung saat mengetik, jadi kamu bisa memangkas bio, caption, atau deskripsi sampai persis di bawah batas platform."),
         ("Bagaimana waktu baca dihitung?",
          "Waktu baca memakai patokan ±220 kata per menit (kecepatan baca dewasa rata-rata); waktu bicara ±130 kata per menit, tempo presentasi yang nyaman. Keduanya perkiraan untuk perencanaan, bukan stopwatch."),
         ("Apa yang dihitung sebagai kalimat dan paragraf?",
          "Kalimat dipisah pada akhiran ., !, dan ?; paragraf pada baris kosong. Teks yang belum diberi tanda titik tetap dihitung satu kalimat, bukan nol."),
         ("Apakah teks saya disimpan?",
          "Tidak. Penghitungan terjadi di browser selagi kamu mengetik; tidak ada yang dikirim atau disimpan. Aman untuk menempel draf rahasia sekalipun.")],
   related=["password-generator","qr-code","signature"]),

 "signature": dict(
   title="Buat Tanda Tangan Online — PNG Transparan Gratis | Fileloka",
   h1="Gambar tanda tangan, simpan jadi PNG transparan",
   lead="Tanda tangani dengan mouse, jari, atau stylus lalu unduh gambar tanda tangan yang bersih — PNG transparan untuk ditempel di dokumen Word/PDF, atau berlatar putih untuk formulir. Goresan halus, bisa undo, pilihan warna tinta, dan tidak ada yang di-upload.",
   meta="Buat tanda tangan online gratis — gambar dengan jari atau mouse, unduh PNG transparan siap tempel di Word dan PDF. Diproses di perangkatmu.",
   steps=["Gambar tanda tanganmu di area yang tersedia — mouse, jari, atau stylus sama-sama bisa.",
          "Atur warna dan ketebalan pena; pakai Undo untuk memperbaiki goresan.",
          "Unduh sebagai PNG — transparan secara bawaan, atau centang latar putih."],
   faqs=[("Bagaimana memasang tanda tangan ini ke dokumen atau PDF?",
          "Unduh PNG transparannya, lalu sisipkan sebagai gambar di Word, Google Docs, atau editor PDF-mu dan letakkan di baris tanda tangan. Karena latarnya transparan, hasilnya menyatu rapi di halaman mana pun."),
         ("Apakah tanda tangan gambar seperti ini sah?",
          "Untuk banyak keperluan sehari-hari — surat, formulir, dokumen internal — gambar tanda tangan umum diterima. Untuk kontrak bernilai tinggi atau dokumen resmi tertentu, pihak penerima kadang mensyaratkan tanda tangan elektronik tersertifikasi (mis. e-meterai/PSrE); alat ini membuat gambarnya, bukan sertifikatnya."),
         ("Kenapa hasilnya terlihat halus meski digambar pakai jari?",
          "Goresan dirender dengan penghalusan kurva dan skala layar tajam (high-DPI), jadi PNG hasil unduhan tetap bersih walau digambar dengan ujung jari di HP."),
         ("Tanda tangan saya di-upload atau disimpan?",
          "Tidak — hanya ada di browser selama kamu menggambar dan di PNG yang kamu unduh. Tutup tab, hilang. Persis seperti seharusnya untuk sesuatu sepribadi tanda tangan.")],
   related=["jpg-to-pdf","merge-pdf","word-counter"]),
}

# Nama tampilan per bahasa (kartu, judul widget terkait, JSON-LD)
NAMES = {
 "merge-pdf":         {"en":"Merge PDF",          "id":"Gabung PDF"},
 "split-pdf":         {"en":"Split PDF",          "id":"Pisah PDF"},
 "compress-pdf":      {"en":"Compress PDF",       "id":"Kompres PDF"},
 "pdf-to-jpg":        {"en":"PDF to JPG",         "id":"PDF ke JPG"},
 "jpg-to-pdf":        {"en":"Images to PDF",      "id":"Foto ke PDF"},
 "compress-image":    {"en":"Compress image",     "id":"Kompres Foto"},
 "resize-image":      {"en":"Resize image",       "id":"Resize Foto"},
 "convert-image":     {"en":"Convert image",      "id":"Konversi Foto"},
 "qr-code":           {"en":"QR code maker",      "id":"Buat QR Code"},
 "password-generator":{"en":"Password generator", "id":"Generator Password"},
 "word-counter":      {"en":"Word counter",       "id":"Penghitung Kata"},
 "signature":         {"en":"Signature maker",    "id":"Tanda Tangan"},
}

CARD_DESC_ID = {
 "merge-pdf":"Satukan beberapa PDF jadi satu file, urutan sesukamu.",
 "split-pdf":"Ambil halaman tertentu, atau simpan tiap halaman terpisah.",
 "compress-pdf":"Perkecil ukuran PDF agar lolos batas email dan unggahan.",
 "pdf-to-jpg":"Ubah tiap halaman PDF jadi gambar berkualitas.",
 "jpg-to-pdf":"Rapikan foto dan scan jadi satu dokumen PDF.",
 "compress-image":"Kecilkan ukuran foto tanpa terlihat pecah.",
 "resize-image":"Ubah ukuran gambar ke piksel atau persen.",
 "convert-image":"Tukar format JPG, PNG, dan WebP sekali klik.",
 "qr-code":"Ubah link atau teks jadi kode siap scan.",
 "password-generator":"Password kuat dan acak, dibuat di perangkatmu.",
 "word-counter":"Kata, karakter, dan waktu baca secara live.",
 "signature":"Gambar tanda tangan, unduh PNG transparan.",
}

UI = {
 "en": dict(back="All tools", how="How it works", faq="Questions about this tool",
            rel="Related tools", open_tool="Open tool",
            pill="0 files uploaded — ever", lang_link="ID"),
 "id": dict(back="Semua alat", how="Cara pakai", faq="Pertanyaan seputar alat ini",
            rel="Alat terkait", open_tool="Buka alat",
            pill="0 file di-upload — selamanya", lang_link="EN"),
}

HOME_ID = dict(
 title="Fileloka — Alat PDF & Foto Gratis, Tanpa Upload",
 meta="Kumpulan alat PDF dan foto gratis: gabung, pisah, kompres PDF, foto ke PDF, kompres foto, WebP ke JPG, dan lainnya. Semua diproses di perangkatmu — tanpa upload.",
 h1='Bereskan file kamu <span class="hl">tanpa meng-upload-nya.</span>',
 lede='Fileloka adalah kotak alat gratis untuk PDF dan gambar. Semuanya berjalan lokal di perangkatmu sendiri — <strong>tanpa upload, tanpa akun, tanpa antre server.</strong>',
 proof=["File tidak pernah meninggalkan perangkatmu","Gratis, tanpa daftar",
        "Tanpa watermark & batas","Jalan di HP dan laptop"],
 search_ph="Cari alat… coba \u201cgabung\u201d atau \u201ckompres\u201d",
 tabs=[("all","Semua alat"),("pdf","PDF"),("image","Gambar"),("util","Harian")],
 grid_empty="Tidak ada alat yang cocok — coba \u201cPDF\u201d, \u201cfoto\u201d, atau \u201cQR\u201d.",
 why_h="Dibangun terbalik dari situs lain",
 why=["Situs alat file pada umumnya bekerja begini: file-mu di-upload ke server mereka, diproses di sana, lalu mereka berjanji menghapusnya \u201cbeberapa jam kemudian\u201d. Kamu diminta percaya.",
      "Fileloka membalik urutannya: tidak ada server sama sekali. Alat-alatnya diunduh ke browser-mu, lalu bekerja di situ. Buktikan sendiri — buka salah satu alat, aktifkan mode pesawat, dan semuanya tetap berjalan. Itu juga alasan semuanya terasa cepat: tidak ada waktu terbuang untuk upload."],
 faq_h="Pertanyaan yang sering diajukan",
 faqs=[("Beneran gratis? Batasnya apa?",
        "Gratis, tanpa akun, tanpa watermark, dan tanpa batas jumlah pemakaian. Batas ukuran file pun tidak dibuat-buat — batasnya hanya kemampuan perangkatmu sendiri, karena memang perangkatmu yang bekerja."),
       ("Bagaimana saya tahu file saya tidak di-upload?",
        "Dua cara: buka DevTools browser \u2192 tab Network saat memakai alat, tidak ada permintaan berisi file; atau setelah halaman terbuka, putuskan internet/aktifkan mode pesawat — alatnya tetap jalan. Kode sumbernya juga terbuka di GitHub."),
       ("Bisa dipakai di HP?",
        "Bisa — semua alat berjalan di browser HP (Chrome, Safari) tanpa install aplikasi. Untuk PDF yang sangat besar, laptop memang lebih bertenaga, tapi pemakaian sehari-hari lancar di HP."),
       ("PDF yang terkunci password bisa diproses?",
        "Belum. File terenkripsi terdeteksi dan diberi tanda dengan jelas, bukan diproses setengah-setengah. Buka dulu kuncinya, baru proses di sini."),
       ("Boleh dipakai untuk keperluan kerja atau usaha?",
        "Boleh sepenuhnya — dokumen kantor, berkas klien, materi jualan. Justru karena tidak pernah di-upload, alat ini lebih pantas dipakai untuk dokumen sensitif dibanding situs yang menyimpan filemu di server mereka.")],
 privacy_h="Privasi, dalam bahasa manusia",
 privacy=["Fileloka tidak mengumpulkan apa pun: tidak ada akun, tidak ada cookie pelacak, tidak ada analytics, dan yang terpenting — tidak ada file yang dikirim ke server, karena servernya memang tidak ada. Yang kamu proses di sini sepenuhnya urusan perangkatmu sendiri.",
          "Ada pertanyaan? Hubungi rizkynandapr@gmail.com."],
 footer_links=[("Beranda","/id/"),("FAQ","/id/#faq"),("Privasi","/id/#privacy"),("English","/")],
)
