# -*- coding: utf-8 -*-
"""Konten Bahasa Indonesia untuk halaman /id/ Fileloka.

Ditulis untuk cara orang Indonesia mencari (bukan terjemahan literal).
Aturan gaya (humanizer, Sep 2026): bahasa sehari-hari pakai "kamu",
tanpa em dash, tanda kutip lurus, tidak menumpuk "tanpa X, tanpa Y, tanpa Z".
"""

P_ID = {
 "merge-pdf": dict(
   title="Gabung PDF Online Gratis, Tanpa Upload | Fileloka",
   h1="Gabungkan beberapa PDF jadi satu file",
   lead="Satukan dua PDF atau lebih dengan urutan yang kamu mau. Prosesnya jalan di HP atau laptopmu sendiri, jadi ijazah, kontrak, dan berkas penting lain tidak pernah dikirim ke server siapa pun.",
   meta="Cara gabung file PDF jadi satu, gratis dan tanpa upload. Atur urutannya dulu, lalu gabungkan langsung di perangkatmu.",
   steps=["Pilih dua PDF atau lebih, atau seret ke halaman ini. Bisa dari HP maupun laptop.",
          "Atur urutannya pakai tombol panah. Jumlah halaman tiap file ikut ditampilkan.",
          "Klik Gabung, lalu unduh PDF hasilnya."],
   faqs=[("Bagaimana cara gabung PDF di HP?",
          "Buka halaman ini di Chrome atau Safari, ketuk area pilih file, lalu ambil PDF dari penyimpanan atau folder WhatsApp. Atur urutannya, ketuk Gabung. Tidak perlu install aplikasi."),
         ("Ada batas jumlah atau ukuran file?",
          "Tidak ada batas yang sengaja dibuat. Batasnya cuma memori perangkatmu, dan puluhan dokumen biasa masih lancar di HP atau laptop sekarang."),
         ("Kualitas dokumennya berubah setelah digabung?",
          "Tidak. Halaman disalin apa adanya. Teks tetap bisa diseleksi dan dicari, gambar tetap tajam, link tetap bisa diklik."),
         ("File saya benar-benar aman?",
          "Aman, karena filenya tidak ke mana-mana. Situs lain meng-upload file ke server lalu janji menghapusnya nanti. Di sini servernya memang tidak ada. Mau bukti? Setelah halaman terbuka, nyalakan mode pesawat. Alatnya tetap jalan.")],
   related=["split-pdf","compress-pdf","jpg-to-pdf"]),

 "split-pdf": dict(
   title="Pisah PDF dan Ambil Halaman Tertentu, Gratis | Fileloka",
   h1="Pisah PDF dan ambil halaman yang kamu butuhkan",
   lead="Ambil halaman atau rentang tertentu dari PDF (misalnya 1-3 dan 7), atau simpan setiap halaman jadi file sendiri. Semuanya diproses di perangkatmu, jadi isi dokumen tidak pernah dilihat server mana pun.",
   meta="Ambil halaman tertentu dari PDF atau pecah tiap halaman jadi file sendiri. Gratis, tanpa upload. Ketik rentang seperti 1-3, 7 lalu unduh.",
   steps=["Pilih PDF yang mau dipisah, atau seret ke halaman ini.",
          "Pilih mode: ambil rentang halaman (contoh 1-3, 7) atau jadikan tiap halaman PDF sendiri.",
          "Unduh hasilnya. Kalau filenya banyak, semuanya dijadikan satu ZIP."],
   faqs=[("Bagaimana cara ambil satu halaman saja dari PDF?",
          "Pilih mode 'Ambil halaman', ketik nomor halamannya (5 saja, 2-4, atau gabungan seperti 1-3, 7), lalu unduh. Kamu dapat PDF baru yang isinya cuma halaman itu."),
         ("Bisa pecah PDF jadi satu file per halaman?",
          "Bisa. Pilih 'Setiap halaman jadi PDF sendiri' dan kamu dapat ZIP berisi PDF bernomor, satu per halaman. Praktis buat memecah hasil scan."),
         ("Teksnya masih bisa dicari setelah dipisah?",
          "Masih. Halamannya disalin, bukan difoto ulang, jadi teks tetap bisa diseleksi, dicari, dan di-copy."),
         ("Dokumen saya di-upload waktu diproses?",
          "Tidak. File dibaca ke memori browser, dipisah di situ, dan hilang begitu tab ditutup. Internet diputus setelah halaman terbuka pun alatnya tetap jalan.")],
   related=["merge-pdf","pdf-to-jpg","compress-pdf"]),

 "compress-pdf": dict(
   title="Kompres PDF Online Gratis, Bisa sampai 200 KB | Fileloka",
   h1="Kompres PDF, teks tetap tajam",
   lead="Kecilkan ukuran PDF langsung di browser. Mode Pintar cuma mengompres foto dan hasil scan di dalamnya, jadi teks tetap bisa diseleksi. Kalau formulir minta di bawah 200 KB, 500 KB, atau 1 MB, pakai mode Target ukuran dan Fileloka yang carikan kualitas terbaik yang masih muat.",
   meta="Kompres PDF gratis tanpa upload. Mode Pintar menjaga teks tetap utuh, mode Target ukuran otomatis pas di bawah 100 KB, 200 KB, 500 KB, atau 1 MB.",
   steps=["Pilih PDF yang mau dikecilkan, atau seret ke halaman ini.",
          "Pilih Pintar (teks utuh), Target ukuran (misalnya 200 KB), atau Maksimal (paling kecil).",
          "Lihat ukuran sebelum dan sesudahnya, lalu unduh."],
   faqs=[("Bagaimana cara kompres PDF jadi 200 KB?",
          "Pilih mode Target ukuran, klik 200 KB (atau ketik ukuran lain), lalu tekan Kompres. Fileloka mencoba mempertahankan teks dulu. Kalau belum cukup, baru dicari kualitas gambar tertinggi yang masih muat. Kamu tidak perlu coba-coba geser slider."),
         ("Apa bedanya mode Pintar dan Maksimal?",
          "Pintar hanya mengompres ulang gambar di dalam PDF. Teks, link, dan grafiknya tetap seperti aslinya. Maksimal menggambar ulang setiap halaman jadi gambar. Hasilnya paling kecil, tapi teksnya tidak bisa diseleksi atau dicari lagi."),
         ("Bisa kompres PDF di HP tanpa aplikasi?",
          "Bisa. Buka halaman ini di Chrome atau Safari, pilih PDF dari penyimpanan atau WhatsApp, lalu kompres. Semuanya jalan di browser."),
         ("Aman untuk dokumen penting seperti ijazah atau KTP?",
          "Aman, justru karena filenya tidak di-upload. Kompresi terjadi di perangkatmu sendiri dan tidak ada server yang menerima file itu. Ini soal cara kerja alatnya, bukan sekadar janji di kebijakan privasi.")],
   related=["merge-pdf","split-pdf","compress-image"]),

 "pdf-to-jpg": dict(
   title="Ubah PDF ke JPG Online Gratis | Fileloka",
   h1="Ubah halaman PDF jadi gambar JPG",
   lead="Simpan tiap halaman PDF sebagai JPG, misalnya buat dikirim lewat WhatsApp, dipasang di slide, atau diunggah ke formulir yang cuma terima gambar. Atur kualitasnya, cek pratinjaunya, lalu unduh satu per satu atau sekaligus dalam ZIP.",
   meta="Ubah PDF ke JPG gratis tanpa upload. Atur kualitas dan resolusi, lihat pratinjau halaman, unduh per gambar atau ZIP.",
   steps=["Pilih PDF atau seret ke halaman ini.",
          "Atur kualitas JPG dan tingkat detail (layar, cetak, atau maksimal).",
          "Konversi, cek pratinjaunya, lalu unduh per gambar atau sekaligus dalam ZIP."],
   faqs=[("Bagaimana cara mengubah PDF ke JPG di HP?",
          "Buka halaman ini di browser HP, pilih PDF-nya, lalu ketuk Konversi. Tiap halaman jadi satu JPG yang bisa langsung disimpan ke galeri atau dikirim lewat WhatsApp."),
         ("Resolusi JPG-nya berapa?",
          "Kamu yang pilih. Good (layar) kira-kira 1,5 kali ukuran halaman, Sharp (cetak) 2 kali, Maximum 3 kali. Makin detail, makin besar filenya."),
         ("Kenapa PDF tertentu lebih lama?",
          "Tiap halaman benar-benar digambar oleh perangkatmu memakai pdf.js, mesin yang sama dengan penampil PDF di Firefox. Dokumen yang panjang atau penuh grafik memang butuh kerja lebih. Progresnya kelihatan di bar."),
         ("Isi PDF-nya di-upload saat dikonversi?",
          "Tidak. Halaman digambar di browser-mu sendiri. Kamu bisa cek sendiri di tab Network, tidak ada yang terkirim.")],
   related=["jpg-to-pdf","compress-image","split-pdf"]),

 "jpg-to-pdf": dict(
   title="Ubah Foto ke PDF (JPG ke PDF) Gratis | Fileloka",
   h1="Ubah foto dan hasil scan jadi satu PDF",
   lead="Gabungkan foto KTP, hasil scan, atau screenshot (JPG, PNG, WebP) jadi satu PDF yang rapi. Urutannya bisa diatur, ukuran halaman bisa ikut foto atau A4, dan margin bisa ditambah. Fotonya tetap di perangkatmu.",
   meta="Ubah JPG, PNG, atau WebP jadi satu PDF gratis tanpa upload. Atur urutan, pilih A4 atau ukuran asli, tambah margin.",
   steps=["Pilih foto-fotonya atau seret ke halaman ini. Formatnya boleh campur.",
          "Atur urutan dan pilih ukuran halaman: ikut ukuran foto, A4 tegak, atau A4 mendatar.",
          "Klik Buat PDF, lalu unduh."],
   faqs=[("Bagaimana cara menjadikan beberapa foto jadi satu PDF di HP?",
          "Pilih semua foto dari galeri sekaligus, atur urutannya, lalu buat PDF. Cocok buat mengumpulkan scan berkas lamaran atau tugas. Foto HEIC dari iPhone perlu diubah dulu lewat alat HEIC ke JPG."),
         ("Sebaiknya pilih ukuran halaman yang mana?",
          "'Ikut ukuran foto' menjaga proporsi aslinya, pas untuk screenshot. A4 menaruh foto rapi di halaman standar, lebih cocok untuk dicetak atau diserahkan ke instansi."),
         ("Fotonya dikompres?",
          "JPG dimasukkan apa adanya, jadi kualitasnya tidak turun. PNG dan WebP juga dimasukkan tanpa kehilangan kualitas."),
         ("Benar-benar privat?",
          "Ya. PDF-nya dirakit di memori browser memakai pdf-lib. Foto kamu tidak dikirim atau disimpan di mana pun.")],
   related=["heic-to-jpg","compress-image","pdf-to-jpg"]),

 "heic-to-jpg": dict(
   title="HEIC ke JPG: Ubah Foto iPhone Gratis | Fileloka",
   h1="Ubah foto iPhone (HEIC) jadi JPG",
   lead="iPhone menyimpan foto dalam format HEIC, dan Windows, aplikasi lama, serta banyak formulir online menolaknya. Di sini fotonya diubah jadi JPG biasa langsung di perangkatmu.",
   meta="Ubah foto HEIC dari iPhone ke JPG gratis tanpa upload. Bisa banyak sekaligus dan kualitasnya bisa diatur.",
   steps=["Pilih foto .heic atau .heif. Beberapa sekaligus juga boleh.",
          "Pilih JPG (bisa dibuka di mana saja) atau PNG, lalu atur kualitasnya.",
          "Konversi, lalu unduh per foto atau sekaligus dalam ZIP."],
   faqs=[("Kenapa file HEIC tidak bisa dibuka di Windows atau diunggah ke formulir?",
          "HEIC itu format milik Apple. Windows dan banyak situs butuh codec tambahan atau langsung menolak file-nya. JPG bisa dibuka di semua perangkat dan diterima semua formulir."),
         ("Bisa ubah banyak foto iPhone sekaligus?",
          "Bisa. Pilih sebanyak yang kamu mau, fotonya diubah satu per satu dengan progres yang kelihatan. Karena perangkatmu yang bekerja, tidak ada antrean upload."),
         ("Kualitasnya turun kalau jadi JPG?",
          "JPG memang lossy, tapi di kualitas bawaan 88 persen bedanya tidak kelihatan saat dilihat atau dicetak. Kalau butuh salinan persis, pilih PNG, meski filenya jauh lebih besar."),
         ("Kok bisa tanpa server?",
          "Halaman ini memuat libheif, decoder open source yang sudah dikompilasi ke JavaScript (sekitar 0,5 MB, sekali saja). Setelah itu browser-mu yang membaca fotonya. Karena itu juga alatnya tetap jalan walau internet diputus.")],
   related=["compress-image","jpg-to-pdf","convert-image"]),

 "compress-image": dict(
   title="Kompres Foto Online Gratis, JPG, PNG, WebP | Fileloka",
   h1="Kompres foto tanpa bikin pecah",
   lead="Kecilkan ukuran foto buat formulir online, lampiran email, atau website yang lebih cepat. Bisa banyak sekaligus, lebarnya bisa dibatasi, dan penghematan tiap file ditampilkan.",
   meta="Kompres foto JPG, PNG, dan WebP gratis tanpa upload. Bisa banyak sekaligus, kualitas dan lebar maksimal bisa diatur, data EXIF dibuang otomatis.",
   steps=["Pilih satu atau beberapa foto, atau seret ke halaman ini.",
          "Atur kualitas, format hasil (JPG, WebP, atau tetap), dan lebar maksimal kalau perlu.",
          "Kompres, lalu unduh per file atau sekaligus dalam ZIP. Ukuran sebelum dan sesudah ditampilkan."],
   faqs=[("Bagaimana cara kompres foto jadi di bawah 200 KB?",
          "Pilih format JPG, turunkan kualitas ke sekitar 70 persen, dan isi lebar maksimal (misalnya 1200 px). Hasil tiap file langsung kelihatan. Kalau masih kebesaran, turunkan lagi sedikit."),
         ("Seberapa kecil hasilnya?",
          "Foto dari HP biasanya menyusut 60 sampai 90 persen di pengaturan bawaan, dan di layar tampilannya tetap sama."),
         ("Kenapa PNG saya tidak mengecil?",
          "PNG itu lossless, jadi slider kualitas tidak berpengaruh. Isi lebar maksimal untuk memperkecil dimensinya, atau ubah ke JPG atau WebP supaya jauh lebih kecil."),
         ("Foto saya di-upload?",
          "Tidak. Kompresi dilakukan mesin gambar bawaan browser di perangkatmu. Bonusnya, data EXIF seperti lokasi GPS ikut dibuang saat disimpan jadi JPG atau WebP.")],
   related=["heic-to-jpg","resize-image","convert-image"]),

 "resize-image": dict(
   title="Resize Foto Online Gratis, Ubah Ukuran Piksel | Fileloka",
   h1="Ubah ukuran foto ke piksel atau persen",
   lead="Sesuaikan ukuran gambar untuk foto profil, marketplace, atau syarat formulir. Proporsinya bisa dijaga otomatis atau lebar dan tingginya diatur persis, untuk satu foto atau banyak sekaligus.",
   meta="Ubah ukuran foto JPG, PNG, dan WebP gratis tanpa upload. Atur piksel persis atau persen, bisa banyak sekaligus, proporsi terjaga otomatis.",
   steps=["Pilih foto yang mau di-resize, atau seret ke halaman ini.",
          "Isi lebar, tinggi, atau keduanya dalam piksel. Bisa juga pakai persen.",
          "Resize lalu unduh. Ukuran barunya ditambahkan ke nama file."],
   faqs=[("Bagaimana cara resize foto untuk pas foto atau formulir?",
          "Isi lebar dan tinggi sesuai yang diminta (misalnya 400 x 600 px). Kalau 'Jaga proporsi' aktif, fotonya dimasukkan pas ke kotak itu tanpa gepeng."),
         ("Bagaimana supaya foto tidak gepeng?",
          "Biarkan 'Jaga proporsi' menyala. Isi lebarnya saja (atau tingginya saja), sisi lainnya dihitung otomatis."),
         ("Kualitasnya turun setelah di-resize?",
          "Kalau diperkecil, gambar tetap tajam. JPG disimpan di kualitas 92 persen, yang di foto tidak kelihatan bedanya. PNG tetap lossless."),
         ("Foto saya di-upload?",
          "Tidak. Resize dilakukan di canvas browser, di perangkatmu sendiri.")],
   related=["compress-image","convert-image","jpg-to-pdf"]),

 "convert-image": dict(
   title="Konversi Foto: WebP ke JPG, PNG ke JPG, Gratis | Fileloka",
   h1="Ubah format foto antara JPG, PNG, dan WebP",
   lead="Ganti format dalam sekali klik. WebP ke JPG supaya bisa dibuka di mana saja, JPG ke PNG untuk diedit, atau apa pun ke WebP biar lebih ringan di website. Bisa banyak sekaligus dan tidak ada yang di-upload.",
   meta="Ubah format gambar WebP ke JPG, PNG ke JPG, dan sebaliknya. Gratis, tanpa upload, bisa banyak file sekaligus.",
   steps=["Pilih foto yang mau diubah. Formatnya boleh campur.",
          "Pilih format tujuan dan, untuk JPG atau WebP, kualitasnya.",
          "Konversi, lalu unduh per file atau sekaligus dalam ZIP."],
   faqs=[("Bagaimana cara ubah WebP ke JPG?",
          "Pilih file WebP, set format tujuan ke JPG, klik Konversi. Hasilnya bisa dibuka di semua aplikasi dan diterima formulir yang menolak WebP."),
         ("Sebaiknya pakai format apa?",
          "JPG untuk foto dan yang harus bisa dibuka di mana saja. PNG untuk screenshot, logo, dan gambar transparan. WebP untuk file paling ringan di website. Kalau ragu, pilih JPG."),
         ("Bagian transparan jadi apa kalau diubah ke JPG?",
          "JPG tidak bisa menyimpan transparansi, jadi bagian itu diberi latar putih bersih. Lebih baik kami bilang dari awal daripada kamu kaget ada kotak hitam."),
         ("Konversinya di server?",
          "Tidak. Browser-mu sendiri yang menyimpan ulang gambarnya, makanya terasa instan.")],
   related=["compress-image","resize-image","pdf-to-jpg"]),

 "qr-code": dict(
   title="Buat QR Code Gratis, Unduh PNG | Fileloka",
   h1="Buat QR code untuk link atau teks apa pun",
   lead="Ketik link, info Wi-Fi, atau teks apa saja, dan dalam beberapa detik kamu dapat QR code yang siap dipasang di layar, brosur, atau banner. Kamu tidak perlu daftar, tidak ada watermark, dan kodenya dibuat di perangkatmu.",
   meta="Buat QR code gratis tanpa daftar dan tanpa watermark. Unduh PNG ukuran layar, cetak, atau poster.",
   steps=["Ketik atau tempel link atau teksnya.",
          "Pilih ukuran: 256 px untuk layar, 512 px untuk cetak, 1024 px untuk poster atau banner.",
          "Klik Buat, lalu unduh PNG-nya."],
   faqs=[("QR code-nya bisa kedaluwarsa?",
          "Tidak akan. Isinya langsung teks atau link kamu, tanpa layanan perantara yang bisa tutup atau tiba-tiba minta bayaran."),
         ("Boleh dipakai untuk jualan atau usaha?",
          "Boleh. Pasang di kemasan, menu, brosur, atau stiker toko. Gambarnya milikmu dan tidak perlu mencantumkan kami."),
         ("Muat teks sepanjang apa?",
          "Satu link atau beberapa ratus karakter masih nyaman. Kalau kepanjangan, alatnya memberi tahu. Isi yang pendek juga lebih cepat di-scan dari jauh."),
         ("Yang saya ketik dikirim ke server?",
          "Tidak. Kodenya digambar di browser. Ini penting kalau isinya link pribadi, password Wi-Fi, atau nomor kontak.")],
   related=["password-generator","word-counter","signature"]),

 "password-generator": dict(
   title="Generator Password Kuat dan Acak, Gratis | Fileloka",
   h1="Buat password kuat dan acak",
   lead="Buat password yang benar-benar acak memakai mesin kriptografi bawaan browser. Panjang, jenis karakter, dan opsi menghindari huruf yang mirip bisa kamu atur. Meternya menampilkan entropi dalam bit, bukan sekadar warna.",
   meta="Generator password kuat gratis yang jalan di perangkatmu. Acak secara kriptografis, panjang dan karakter bisa diatur, entropi ditampilkan dalam bit.",
   steps=["Atur panjangnya (16 karakter ke atas lebih disarankan) dan jenis karakter yang dipakai.",
          "Nyalakan opsi hindari karakter mirip (l, 1, O, 0) kalau password-nya akan diketik manual.",
          "Salin password-nya. Setiap kamu ubah pengaturan, password baru langsung dibuat."],
   faqs=[("Generator ini benar-benar aman?",
          "Aman. Ia memakai crypto.getRandomValues, sumber acak yang sama dengan pengelola password, dengan sampling yang tidak berat sebelah, dan memastikan tiap jenis karakter yang kamu pilih ikut muncul. Kodenya open source kalau mau dicek."),
         ("Apa arti angka bit entropi?",
          "Entropi mengukur seberapa sulit password ditebak dengan brute force. Kira-kira 45 bit itu lemah, 70 lumayan, 100 ke atas sangat kuat. Password 16 karakter dengan semua jenis karakter ada di sekitar 100 bit."),
         ("Password-nya disimpan atau dikirim?",
          "Tidak. Password dibuat di memori browser dan cuma ada di layar serta clipboard-mu. Muat ulang halaman, password-nya hilang."),
         ("Perlu menghindari karakter yang mirip?",
          "Nyalakan untuk password yang akan kamu baca dan ketik sendiri, misalnya Wi-Fi. Untuk password yang disimpan di pengelola password, biarkan mati supaya pilihan karakternya lebih banyak.")],
   related=["qr-code","word-counter","signature"]),

 "word-counter": dict(
   title="Hitung Jumlah Kata dan Karakter Online | Fileloka",
   h1="Hitung kata, karakter, dan waktu baca",
   lead="Tempel atau ketik teks dan angkanya langsung berubah: jumlah kata, karakter dengan dan tanpa spasi, kalimat, paragraf, kata unik, plus perkiraan waktu baca dan waktu bicara. Pas buat esai, caption, atau naskah presentasi.",
   meta="Hitung jumlah kata, karakter, kalimat, paragraf, dan waktu baca secara live. Gratis, teks kamu tidak dikirim ke mana pun.",
   steps=["Tempel atau ketik teks di kotak.",
          "Angkanya ikut berubah saat kamu mengetik. Tidak ada tombol yang perlu ditekan.",
          "Pakai waktu baca (sekitar 220 kata per menit) dan waktu bicara (sekitar 130) untuk menyesuaikan batas."],
   faqs=[("Bisa untuk cek batas kata esai atau skripsi?",
          "Bisa. Tempel bagiannya dan jumlah kata langsung kelihatan. Cocok untuk abstrak, esai beasiswa, atau batas kata tugas."),
         ("Bisa untuk batas karakter caption atau bio?",
          "Bisa. Jumlah karakter, dengan atau tanpa spasi, berubah seketika, jadi kamu bisa memangkas teks pas di batasnya."),
         ("Waktu baca dihitung dari mana?",
          "Waktu baca memakai kecepatan rata-rata sekitar 220 kata per menit, waktu bicara sekitar 130 kata per menit, tempo presentasi yang nyaman. Anggap saja perkiraan."),
         ("Teks saya disimpan?",
          "Tidak. Semua dihitung di browser dan tidak ada yang disimpan atau dikirim. Draf rahasia pun aman ditempel di sini.")],
   related=["password-generator","qr-code","signature"]),

 "signature": dict(
   title="Buat Tanda Tangan Online, PNG Transparan | Fileloka",
   h1="Buat tanda tangan digital, simpan sebagai PNG",
   lead="Tanda tangan pakai jari, mouse, atau stylus, lalu unduh gambarnya. PNG transparan bisa langsung ditempel di dokumen, atau pakai latar putih untuk formulir. Garisnya dihaluskan dan bisa di-undo.",
   meta="Buat tanda tangan online gratis, gambar pakai jari atau mouse, lalu unduh PNG transparan. Diproses di perangkatmu.",
   steps=["Tanda tangan di area yang tersedia pakai jari, mouse, atau stylus.",
          "Atur warna tinta dan ketebalan. Undo menghapus goresan terakhir.",
          "Unduh sebagai PNG. Latarnya transparan, kecuali kamu centang latar putih."],
   faqs=[("Bagaimana cara menempel tanda tangan ke dokumen Word atau PDF?",
          "Unduh PNG transparan, lalu sisipkan sebagai gambar di Word, Google Docs, atau editor PDF, dan geser ke kolom tanda tangan. Karena latarnya transparan, hasilnya menyatu dengan halaman."),
         ("Tanda tangan seperti ini sah?",
          "Untuk banyak dokumen sehari-hari, gambar tanda tangan umumnya diterima. Untuk kontrak penting, tanyakan dulu syarat pihak penerima. Alat ini membuat gambar tanda tangan, bukan tanda tangan elektronik tersertifikasi."),
         ("Kenapa hasilnya halus walau digambar pakai jari?",
          "Goresan diproses dengan penghalus kurva dan resolusi tinggi, jadi PNG-nya tetap rapi walau kamu tanda tangan pakai jari di HP."),
         ("Tanda tangan saya di-upload?",
          "Tidak. Ia cuma ada di browser selama kamu menggambar dan di file PNG yang kamu unduh. Tutup tab, hilang. Untuk hal sepribadi tanda tangan, memang begitu seharusnya.")],
   related=["jpg-to-pdf","merge-pdf","word-counter"]),
}

NAMES = {
 "merge-pdf":         {"en":"Merge PDF",          "id":"Gabung PDF"},
 "split-pdf":         {"en":"Split PDF",          "id":"Pisah PDF"},
 "compress-pdf":      {"en":"Compress PDF",       "id":"Kompres PDF"},
 "pdf-to-jpg":        {"en":"PDF to JPG",         "id":"PDF ke JPG"},
 "jpg-to-pdf":        {"en":"Images to PDF",      "id":"Foto ke PDF"},
 "compress-image":    {"en":"Compress image",     "id":"Kompres Foto"},
 "resize-image":      {"en":"Resize image",       "id":"Resize Foto"},
 "heic-to-jpg":       {"en":"HEIC to JPG",       "id":"HEIC ke JPG"},
 "convert-image":     {"en":"Convert image",      "id":"Konversi Foto"},
 "qr-code":           {"en":"QR code maker",      "id":"Buat QR Code"},
 "password-generator":{"en":"Password generator", "id":"Generator Password"},
 "word-counter":      {"en":"Word counter",       "id":"Penghitung Kata"},
 "signature":         {"en":"Signature maker",    "id":"Tanda Tangan"},
}

CARD_DESC_ID = {
 "merge-pdf":"Satukan beberapa PDF jadi satu, urutannya kamu yang atur.",
 "split-pdf":"Ambil halaman tertentu, atau pecah jadi file per halaman.",
 "compress-pdf":"Kecilkan PDF supaya lolos batas email dan formulir.",
 "pdf-to-jpg":"Simpan tiap halaman PDF sebagai gambar JPG.",
 "jpg-to-pdf":"Kumpulkan foto dan hasil scan jadi satu PDF.",
 "compress-image":"Kecilkan ukuran foto tanpa kelihatan pecah.",
 "resize-image":"Ubah ukuran gambar ke piksel atau persen.",
 "heic-to-jpg":"Ubah foto iPhone (HEIC) jadi JPG biasa.",
 "convert-image":"Tukar format JPG, PNG, dan WebP.",
 "qr-code":"Ubah link atau teks jadi kode yang siap di-scan.",
 "password-generator":"Password acak yang kuat, dibuat di perangkatmu.",
 "word-counter":"Hitung kata, karakter, dan waktu baca.",
 "signature":"Gambar tanda tangan, unduh sebagai PNG transparan.",
}

UI = {
 "en": dict(back="All tools", how="How it works", faq="Questions about this tool",
            rel="Related tools", open_tool="Open tool",
            pill="0 files uploaded", lang_link="ID"),
 "id": dict(back="Semua alat", how="Cara pakai", faq="Pertanyaan soal alat ini",
            rel="Alat lain yang mungkin kamu perlu", open_tool="Buka alat",
            pill="0 file di-upload", lang_link="EN"),
}

HOME_ID = dict(
 title="Fileloka: Alat PDF dan Foto Gratis, File Tidak Di-upload",
 meta="Alat PDF dan foto gratis: kompres, gabung, dan pisah PDF, ubah foto ke PDF, kompres foto, WebP ke JPG, dan lainnya. Semua diproses di perangkatmu, file tidak di-upload.",
 search_ph="Cari alat... coba \"kompres\" atau \"gabung\"",
 grid_empty="Tidak ada alat yang cocok. Coba ketik \"PDF\", \"foto\", atau \"QR\".",
 why_h="Kebalikan dari situs sejenis",
 faq_h="Pertanyaan yang sering muncul",
 faqs=[("Beneran gratis? Ada batasnya?",
        "Gratis. Kamu tidak perlu akun, hasilnya tidak diberi watermark, dan tidak ada batas pemakaian harian. Ukuran file juga tidak dibatasi secara sengaja. Batasnya cuma kemampuan perangkatmu, karena memang perangkatmu yang bekerja."),
       ("Bagaimana saya tahu file saya tidak di-upload?",
        "Ada dua cara. Buka DevTools di browser, tab Network, lalu pakai salah satu alat: tidak ada permintaan yang membawa file. Atau, setelah halaman terbuka, nyalakan mode pesawat. Alatnya tetap jalan. Kode sumbernya juga terbuka di GitHub."),
       ("Bisa dipakai di HP?",
        "Bisa. Semua alat jalan di browser HP (Chrome atau Safari) tanpa install apa-apa. Untuk PDF yang sangat besar laptop memang lebih cepat, tapi untuk pemakaian sehari-hari HP sudah lancar."),
       ("PDF yang dikunci password bisa diproses?",
        "Belum. File terkunci akan diberi tanda dan dilewati, bukan diproses setengah jalan. Buka kuncinya dulu, baru proses di sini."),
       ("Boleh dipakai untuk kerjaan atau usaha?",
        "Boleh. Justru karena filenya tidak di-upload, Fileloka lebih cocok untuk dokumen kantor dan berkas klien dibanding situs yang menyimpan file di server mereka.")],
 privacy_h="Soal privasi, singkatnya",
)
